### PR TITLE
Publish RFC :: 0001-working-in-the-open.md

### PR DESCRIPTION
**Pull request by obrien-j**
# Summary | Résumé

Initial attempt at publishing a 'Working in the Open' strategy, while also putting into place RFC's as a way to drive discussion of upcoming features / changes.

# Help requested | Aide requise

[x] Translation before publishing would be ideal.

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [x ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?

### CODE REVIEW

**Review by CalvinRodo — APPROVED** [review]
👍🏼

**Comment by LeCanardQuoi** [comment]
Who is going to participate to this? And what exactly is being attempted first?

**Comment by obrien-j** [comment]
Thanks @EliseKa for the quick turnaround on translation. Merging as is.

**Comment by obrien-j** [comment]
Hey @LeCanardQuoi 

> Who is going to participate to this? 

This is written with 'we' referring to the Covid Alert teams here at the Canadian Digital Service.

>And what exactly is being attempted first? 

I'd refer you back to the RFC as written, it's an attempt at getting more of our work, outside of just the development, more into the open.

>Also, if I understand this correctly, no more enhancement request issues are allowed (from the public or core users)??? 

That is not the intent, it's more to help the teams focus on their inflight tasks in their individual repositories, while creating a more central place for outside collaborators to raise ideas, questions and to start discussions. 

>The process of managing new reqs (entered via these ERs) remains unclear and opaque imo, i.e. no traceability on decision making which is what I was mainly seeking as part of a "stronger response plan" from the Covid Alert app.

I hope this and future work helps to clear this up for you and others. We'll be publishing the 'Product Decision Framwork' shortly, which should answer some of your questions.

Stay tuned!

**Comment by obrien-j** [comment]
Closes his own PR. What a champ! 🥇

**Pull request merged**
